import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const DynamicModals = dynamic(() => import("./modal/Modals"), {
    ssr: false
  })

  return (
    <html lang="en">
    <ReduxProvider>
      <body className={inter.className}>
      {children}
      <DynamicModals/>
      </body>
    </ReduxProvider>
    </html>
  );
}
